# Shared settings for local environment
kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  topics:
    api: api
    js: js
    project: project
    subdomain: subdomain
  groups:
    certsh: certsh
    getjs: getjs
    linkfinder: linkfinder
    db: db
