name: Publish Common to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - 'common/**'  # Only trigger when changes are made inside the 'common' directory
  workflow_dispatch: # Allows manual trigger

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # Change if needed
          cache: 'gradle'

      - name: Grant Execute Permission to Gradlew
        run: chmod +x ./common/gradlew

      - name: Publish to GitHub Packages
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          cd common
          ./gradlew publish
